package view;

import java.awt.CardLayout;
import model.Cliente;
import model.Fornecedor;
import model.Produto;

public class Tela extends javax.swing.JFrame {

    String painel;

    public Tela() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Sistema de Controle de Estoque");
        mostraPainel("Clientes");
        limpaTelaCliente();
    }
    
      private void mostraPainel(String pn) {
        CardLayout cl = (CardLayout) (pnCentral.getLayout());
        cl.show(pnCentral, pn);
        painel = pn;
    }

    private void limpaTelaCliente() {
        tfNome.setText("");
        tfCPF.setText("");
        tfCelular.setText("");
        tfEmail.setText("");
        tfNome.requestFocus();
    }

    private void limpaTelaProduto() {
        tfDescricao.setText("");
        tfQtde.setText("");
        tfCustoMedio.setText("");
        tfDescricao.requestFocus();
    }

    private void limpaTelaFornecedor() {
        tfCNPJ.setText("");
        tfNomeFornecedor.setText("");
        tfTelefone.setText("");
        tfEmailFornecedor.setText("");
        tfCNPJ.requestFocus();
    }

    private void gravaCliente() {
        String nome = tfNome.getText();
        String cpf = tfCPF.getText();
        String celular = tfCelular.getText();
        String email = tfEmail.getText();
        new Cliente(cpf, nome, celular, email).gravarCliente();
        limpaTelaCliente();
    }

    private void gravaProduto() {
        String descricao = tfDescricao.getText();
        int qtde = Integer.parseInt(tfQtde.getText());
        double custoMedio = Double.parseDouble(tfCustoMedio.getText());
        new Produto(descricao, qtde, custoMedio).gravarProduto();
        limpaTelaProduto();
    }

    private void gravaFornecedor() {
        String cnpj = tfCNPJ.getText();
        String nome = tfNomeFornecedor.getText();
        String telefone = tfTelefone.getText();
        String email = tfEmailFornecedor.getText();
        new Fornecedor(cnpj, nome, telefone, email).gravarFornecedor();
        limpaTelaFornecedor();
    }
    
    private void listaCliente() {
        new TLista(Cliente.getTableModel()).setVisible(true);
    }
    
    private void listaProduto(){
        new TLista(Produto.getTableModel()).setVisible(true);
    }
    
    private void listaFornecedor(){
        new TLista(Fornecedor.getTableModel()).setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnTitulo = new javax.swing.JPanel();
        lbLogo = new javax.swing.JLabel();
        lbTitulo = new javax.swing.JLabel();
        pnBotoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btListar = new javax.swing.JButton();
        btSalvar = new javax.swing.JButton();
        btLimpar = new javax.swing.JButton();
        pnMenu = new javax.swing.JPanel();
        btClientes = new javax.swing.JButton();
        btFornecedores = new javax.swing.JButton();
        btProdutos = new javax.swing.JButton();
        btEntradas = new javax.swing.JButton();
        btSaidas = new javax.swing.JButton();
        pnCentral = new javax.swing.JPanel();
        pnProdutos = new javax.swing.JPanel();
        lbProdutos = new javax.swing.JLabel();
        lbDescricao = new javax.swing.JLabel();
        lbQuantidade = new javax.swing.JLabel();
        lbCustoMedio = new javax.swing.JLabel();
        tfQtde = new javax.swing.JTextField();
        tfCustoMedio = new javax.swing.JTextField();
        tfDescricao = new javax.swing.JTextField();
        pnClientes = new javax.swing.JPanel();
        lbClientes = new javax.swing.JLabel();
        lbNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lbCPF = new javax.swing.JLabel();
        tfCPF = new javax.swing.JTextField();
        lbCelular = new javax.swing.JLabel();
        lbEmail = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        tfCelular = new javax.swing.JTextField();
        pnFornecedores = new javax.swing.JPanel();
        lbFornecedores = new javax.swing.JLabel();
        lbCNPJ = new javax.swing.JLabel();
        lbNomeFornecedor = new javax.swing.JLabel();
        lbTelefone = new javax.swing.JLabel();
        lbEmailFornecedor = new javax.swing.JLabel();
        tfNomeFornecedor = new javax.swing.JTextField();
        tfTelefone = new javax.swing.JTextField();
        tfCNPJ = new javax.swing.JTextField();
        tfEmailFornecedor = new javax.swing.JTextField();
        pnEntradas = new javax.swing.JPanel();
        lbEntradas = new javax.swing.JLabel();
        pnSaidas = new javax.swing.JPanel();
        lbSaidas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnTitulo.setBackground(new java.awt.Color(17, 28, 33));
        pnTitulo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        pnTitulo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbLogo.setBackground(new java.awt.Color(34, 20, 43));
        lbLogo.setForeground(new java.awt.Color(32, 19, 41));
        lbLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/logo.png"))); // NOI18N
        pnTitulo.add(lbLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, -1));

        lbTitulo.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        lbTitulo.setForeground(new java.awt.Color(178, 251, 1));
        lbTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbTitulo.setText("Kardex");
        pnTitulo.add(lbTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 0, 750, 60));

        getContentPane().add(pnTitulo, java.awt.BorderLayout.NORTH);

        pnBotoes.setBackground(new java.awt.Color(51, 51, 51));
        pnBotoes.setPreferredSize(new java.awt.Dimension(595, 38));
        pnBotoes.setLayout(new java.awt.GridLayout(1, 0));
        pnBotoes.add(jLabel1);
        pnBotoes.add(jLabel2);
        pnBotoes.add(jLabel3);

        btListar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btListar.setForeground(new java.awt.Color(178, 251, 1));
        btListar.setText("Listar");
        btListar.setContentAreaFilled(false);
        btListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btListarActionPerformed(evt);
            }
        });
        pnBotoes.add(btListar);

        btSalvar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(178, 251, 1));
        btSalvar.setText("Salvar");
        btSalvar.setContentAreaFilled(false);
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });
        pnBotoes.add(btSalvar);

        btLimpar.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btLimpar.setForeground(new java.awt.Color(178, 251, 1));
        btLimpar.setText("Limpar");
        btLimpar.setContentAreaFilled(false);
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });
        pnBotoes.add(btLimpar);

        getContentPane().add(pnBotoes, java.awt.BorderLayout.SOUTH);

        pnMenu.setBackground(new java.awt.Color(51, 51, 51));
        pnMenu.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        pnMenu.setLayout(new java.awt.GridLayout(0, 1));

        btClientes.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btClientes.setForeground(new java.awt.Color(178, 251, 1));
        btClientes.setText("Clientes");
        btClientes.setBorderPainted(false);
        btClientes.setContentAreaFilled(false);
        btClientes.setMaximumSize(new java.awt.Dimension(109, 32));
        btClientes.setMinimumSize(new java.awt.Dimension(109, 32));
        btClientes.setPreferredSize(new java.awt.Dimension(109, 32));
        btClientes.setRolloverEnabled(true);
        btClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClientesActionPerformed(evt);
            }
        });
        pnMenu.add(btClientes);

        btFornecedores.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btFornecedores.setForeground(new java.awt.Color(178, 251, 1));
        btFornecedores.setText("Fornecedores");
        btFornecedores.setBorderPainted(false);
        btFornecedores.setContentAreaFilled(false);
        btFornecedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFornecedoresActionPerformed(evt);
            }
        });
        pnMenu.add(btFornecedores);

        btProdutos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btProdutos.setForeground(new java.awt.Color(178, 251, 1));
        btProdutos.setText("Produtos");
        btProdutos.setBorderPainted(false);
        btProdutos.setContentAreaFilled(false);
        btProdutos.setMaximumSize(new java.awt.Dimension(109, 32));
        btProdutos.setMinimumSize(new java.awt.Dimension(109, 32));
        btProdutos.setPreferredSize(new java.awt.Dimension(109, 32));
        btProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btProdutosActionPerformed(evt);
            }
        });
        pnMenu.add(btProdutos);

        btEntradas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btEntradas.setForeground(new java.awt.Color(178, 251, 1));
        btEntradas.setText("Entradas");
        btEntradas.setBorderPainted(false);
        btEntradas.setContentAreaFilled(false);
        btEntradas.setMaximumSize(new java.awt.Dimension(109, 32));
        btEntradas.setMinimumSize(new java.awt.Dimension(109, 32));
        btEntradas.setPreferredSize(new java.awt.Dimension(109, 32));
        pnMenu.add(btEntradas);

        btSaidas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btSaidas.setForeground(new java.awt.Color(178, 251, 1));
        btSaidas.setText("Saidas");
        btSaidas.setBorderPainted(false);
        btSaidas.setContentAreaFilled(false);
        btSaidas.setMaximumSize(new java.awt.Dimension(109, 32));
        btSaidas.setMinimumSize(new java.awt.Dimension(109, 32));
        btSaidas.setPreferredSize(new java.awt.Dimension(109, 32));
        pnMenu.add(btSaidas);

        getContentPane().add(pnMenu, java.awt.BorderLayout.WEST);

        pnCentral.setBackground(new java.awt.Color(255, 0, 0));
        pnCentral.setLayout(new java.awt.CardLayout());

        pnProdutos.setBackground(new java.awt.Color(153, 153, 153));

        lbProdutos.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        lbProdutos.setForeground(new java.awt.Color(0, 0, 0));
        lbProdutos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbProdutos.setText("Produtos");

        lbDescricao.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbDescricao.setForeground(new java.awt.Color(0, 0, 0));
        lbDescricao.setText("Descrição:");

        lbQuantidade.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbQuantidade.setForeground(new java.awt.Color(0, 0, 0));
        lbQuantidade.setText("Quantidade:");

        lbCustoMedio.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbCustoMedio.setForeground(new java.awt.Color(0, 0, 0));
        lbCustoMedio.setText("Custo Medio:");

        tfQtde.setPreferredSize(new java.awt.Dimension(14, 32));

        tfCustoMedio.setPreferredSize(new java.awt.Dimension(14, 32));

        tfDescricao.setPreferredSize(new java.awt.Dimension(14, 32));

        javax.swing.GroupLayout pnProdutosLayout = new javax.swing.GroupLayout(pnProdutos);
        pnProdutos.setLayout(pnProdutosLayout);
        pnProdutosLayout.setHorizontalGroup(
            pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProdutosLayout.createSequentialGroup()
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnProdutosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbProdutos, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE))
                    .addGroup(pnProdutosLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDescricao)
                            .addComponent(lbQuantidade)
                            .addComponent(lbCustoMedio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDescricao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfQtde, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfCustoMedio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        pnProdutosLayout.setVerticalGroup(
            pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnProdutosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbProdutos, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbDescricao)
                    .addComponent(tfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbQuantidade)
                    .addComponent(tfQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(pnProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCustoMedio)
                    .addComponent(tfCustoMedio, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        pnCentral.add(pnProdutos, "Produtos");

        pnClientes.setBackground(new java.awt.Color(153, 153, 153));

        lbClientes.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        lbClientes.setForeground(new java.awt.Color(0, 0, 0));
        lbClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbClientes.setText("Clientes");

        lbNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbNome.setForeground(new java.awt.Color(0, 0, 0));
        lbNome.setText("Nome:");

        tfNome.setPreferredSize(new java.awt.Dimension(14, 32));

        lbCPF.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbCPF.setForeground(new java.awt.Color(0, 0, 0));
        lbCPF.setText("CPF:");

        lbCelular.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbCelular.setForeground(new java.awt.Color(0, 0, 0));
        lbCelular.setText("Celular:");

        lbEmail.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbEmail.setForeground(new java.awt.Color(0, 0, 0));
        lbEmail.setText("E-mail:");

        javax.swing.GroupLayout pnClientesLayout = new javax.swing.GroupLayout(pnClientes);
        pnClientes.setLayout(pnClientesLayout);
        pnClientesLayout.setHorizontalGroup(
            pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnClientesLayout.createSequentialGroup()
                .addContainerGap(119, Short.MAX_VALUE)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbEmail)
                    .addComponent(lbNome)
                    .addComponent(lbCelular)
                    .addComponent(lbCPF))
                .addGap(18, 18, 18)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                    .addComponent(tfCPF)
                    .addComponent(tfCelular)
                    .addComponent(tfEmail))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pnClientesLayout.setVerticalGroup(
            pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnClientesLayout.createSequentialGroup()
                .addComponent(lbClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNome))
                .addGap(24, 24, 24)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCPF))
                .addGap(18, 18, 18)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCelular))
                .addGap(16, 16, 16)
                .addGroup(pnClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbEmail))
                .addGap(0, 84, Short.MAX_VALUE))
        );

        pnCentral.add(pnClientes, "Clientes");

        pnFornecedores.setBackground(new java.awt.Color(153, 153, 153));

        lbFornecedores.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        lbFornecedores.setForeground(new java.awt.Color(0, 0, 0));
        lbFornecedores.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbFornecedores.setText("Fornecedores");

        lbCNPJ.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbCNPJ.setForeground(new java.awt.Color(0, 0, 0));
        lbCNPJ.setText("CNPJ:");

        lbNomeFornecedor.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbNomeFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        lbNomeFornecedor.setText("Nome:");

        lbTelefone.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbTelefone.setForeground(new java.awt.Color(0, 0, 0));
        lbTelefone.setText("Telefone:");

        lbEmailFornecedor.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbEmailFornecedor.setForeground(new java.awt.Color(0, 0, 0));
        lbEmailFornecedor.setText("E-mail:");

        tfNomeFornecedor.setPreferredSize(new java.awt.Dimension(14, 32));

        tfTelefone.setPreferredSize(new java.awt.Dimension(14, 32));

        tfCNPJ.setPreferredSize(new java.awt.Dimension(14, 32));

        tfEmailFornecedor.setPreferredSize(new java.awt.Dimension(14, 32));

        javax.swing.GroupLayout pnFornecedoresLayout = new javax.swing.GroupLayout(pnFornecedores);
        pnFornecedores.setLayout(pnFornecedoresLayout);
        pnFornecedoresLayout.setHorizontalGroup(
            pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbFornecedores, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
            .addGroup(pnFornecedoresLayout.createSequentialGroup()
                .addGroup(pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnFornecedoresLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addGroup(pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbCNPJ)
                            .addComponent(lbTelefone)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnFornecedoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbNomeFornecedor, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbEmailFornecedor, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(27, 27, 27)
                .addGroup(pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(tfCNPJ, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(tfNomeFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfEmailFornecedor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnFornecedoresLayout.setVerticalGroup(
            pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnFornecedoresLayout.createSequentialGroup()
                .addComponent(lbFornecedores, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addGroup(pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCNPJ)
                    .addComponent(tfCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNomeFornecedor)
                    .addComponent(tfNomeFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTelefone)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(pnFornecedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbEmailFornecedor)
                    .addComponent(tfEmailFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 64, Short.MAX_VALUE))
        );

        pnCentral.add(pnFornecedores, "Fornecedores");

        pnEntradas.setBackground(new java.awt.Color(153, 153, 153));

        lbEntradas.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        lbEntradas.setForeground(new java.awt.Color(0, 0, 0));
        lbEntradas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbEntradas.setText("Entradas");

        javax.swing.GroupLayout pnEntradasLayout = new javax.swing.GroupLayout(pnEntradas);
        pnEntradas.setLayout(pnEntradasLayout);
        pnEntradasLayout.setHorizontalGroup(
            pnEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        pnEntradasLayout.setVerticalGroup(
            pnEntradasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnEntradasLayout.createSequentialGroup()
                .addComponent(lbEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        pnCentral.add(pnEntradas, "Entradas");

        pnSaidas.setBackground(new java.awt.Color(153, 153, 153));

        lbSaidas.setFont(new java.awt.Font("Verdana", 2, 24)); // NOI18N
        lbSaidas.setForeground(new java.awt.Color(0, 0, 0));
        lbSaidas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbSaidas.setText("Saidas");

        javax.swing.GroupLayout pnSaidasLayout = new javax.swing.GroupLayout(pnSaidas);
        pnSaidas.setLayout(pnSaidasLayout);
        pnSaidasLayout.setHorizontalGroup(
            pnSaidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbSaidas, javax.swing.GroupLayout.DEFAULT_SIZE, 628, Short.MAX_VALUE)
        );
        pnSaidasLayout.setVerticalGroup(
            pnSaidasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnSaidasLayout.createSequentialGroup()
                .addComponent(lbSaidas, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        pnCentral.add(pnSaidas, "Saidas");

        getContentPane().add(pnCentral, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btProdutosActionPerformed
        mostraPainel("Produtos");
    }//GEN-LAST:event_btProdutosActionPerformed

    private void btClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClientesActionPerformed
        mostraPainel("Clientes");
    }//GEN-LAST:event_btClientesActionPerformed

    private void btFornecedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFornecedoresActionPerformed
        mostraPainel("Fornecedores");
    }//GEN-LAST:event_btFornecedoresActionPerformed

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed
        if (painel.equals("Clientes")) {
            gravaCliente();
        } else if (painel.equals("Fornecedores")) {
            gravaFornecedor();
        } else if (painel.equals("Produtos")) {
            gravaProduto();
        }
    }//GEN-LAST:event_btSalvarActionPerformed

    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        if (painel.equals("Clientes")) {
            limpaTelaCliente();
        } else if (painel.equals("Fornecedores")) {
            limpaTelaFornecedor();
        } else if (painel.equals("Produtos")) {
            limpaTelaProduto();
        }
    }//GEN-LAST:event_btLimparActionPerformed

    private void btListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btListarActionPerformed
         if (painel.equals("Clientes")) {
            listaCliente();
        } else if (painel.equals("Fornecedores")) {
            listaFornecedor();
        } else if (painel.equals("Produtos")) {
            listaProduto();
        }
    }//GEN-LAST:event_btListarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClientes;
    private javax.swing.JButton btEntradas;
    private javax.swing.JButton btFornecedores;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btListar;
    private javax.swing.JButton btProdutos;
    private javax.swing.JButton btSaidas;
    private javax.swing.JButton btSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lbCNPJ;
    private javax.swing.JLabel lbCPF;
    private javax.swing.JLabel lbCelular;
    private javax.swing.JLabel lbClientes;
    private javax.swing.JLabel lbCustoMedio;
    private javax.swing.JLabel lbDescricao;
    private javax.swing.JLabel lbEmail;
    private javax.swing.JLabel lbEmailFornecedor;
    private javax.swing.JLabel lbEntradas;
    private javax.swing.JLabel lbFornecedores;
    private javax.swing.JLabel lbLogo;
    private javax.swing.JLabel lbNome;
    private javax.swing.JLabel lbNomeFornecedor;
    private javax.swing.JLabel lbProdutos;
    private javax.swing.JLabel lbQuantidade;
    private javax.swing.JLabel lbSaidas;
    private javax.swing.JLabel lbTelefone;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JPanel pnBotoes;
    private javax.swing.JPanel pnCentral;
    private javax.swing.JPanel pnClientes;
    private javax.swing.JPanel pnEntradas;
    private javax.swing.JPanel pnFornecedores;
    private javax.swing.JPanel pnMenu;
    private javax.swing.JPanel pnProdutos;
    private javax.swing.JPanel pnSaidas;
    private javax.swing.JPanel pnTitulo;
    private javax.swing.JTextField tfCNPJ;
    private javax.swing.JTextField tfCPF;
    private javax.swing.JTextField tfCelular;
    private javax.swing.JTextField tfCustoMedio;
    private javax.swing.JTextField tfDescricao;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEmailFornecedor;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNomeFornecedor;
    private javax.swing.JTextField tfQtde;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
